obj-m = tg.o

all: 
		make -C /home/xrander24/HSSE/2026_linux/root/lib/modules/6.19.0/build M=$(PWD) modules

clean:
		make -C /home/xrander24/HSSE/2026_linux/root/lib/modules/6.19.0/build M=$(PWD) clean
